version: 2.1

orbs:
  python: circleci/python@2.1.1
  browser-tools: circleci/browser-tools@1.4.4

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.7-browsers
    executor: python/default 
    steps:
      - checkout 
      - run:
        python -m pip install --upgrade pip
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: "requirements.txt"
      - run:
          name: Run tests
          command: python3 run_tests.py

workflows:
  build_test:
    jobs:
      - build-and-test

