version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10-browsers
    executor: python/default 
    steps:
      - checkout 
      - run:
          name: update pip
          command: pip install --upgrade pip
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: "requirements.txt"
      - run:
          name: run tests
          command: |
            mkdir test-results
            pytest --junitxml=test-results/junit.xml run_test.py
      - store_test_results:
          path: test-results

workflows:
  build_test:
    jobs:
      - build-and-test


